# Generated by Django 3.0.3 on 2021-05-17 09:44

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('title_en', models.CharField(max_length=70, null=True)),
                ('title_de', models.CharField(max_length=70, null=True)),
                ('content', tinymce.models.HTMLField()),
                ('content_en', tinymce.models.HTMLField(null=True)),
                ('content_de', tinymce.models.HTMLField(null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('HOMEPAGE', 'Homepage'), ('POST', 'Post or Blogpost'), ('PAGE', 'Page')], default='PAGE', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Settings name')),
                ('value', models.CharField(max_length=256, verbose_name='Settings value')),
            ],
        ),
    ]
