# Generated by Django 3.0.3 on 2021-07-16 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        

    ]
