# Generated by Django 3.0.3 on 2021-07-16 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210716_2315'),
    ]

    operations = [
        
    ]
