# Generated by Django 3.0.3 on 2021-07-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210707_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content_de',
            new_name='content',
        ),
    ]
