# Generated by Django 2.2.5 on 2019-10-07 15:09

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Give survey a name', max_length=255, verbose_name='The surveys name')),
                ('description', models.TextField(help_text='Give the survey a short description, so that others know what it us', verbose_name='Short description of the survey')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('introduction', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(unpack_ipv4=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey', verbose_name='Related survey')),
            ],
        ),
    ]
