# Generated by Django 2.2.5 on 2019-10-07 19:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='introduction',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
