# Generated by Django 2.2.5 on 2019-10-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_survey_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Factor Name')),
                ('blockfactor', models.BooleanField(verbose_name='Block factor')),
            ],
        ),
        migrations.CreateModel(
            name='SetLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Factor Name')),
                ('value', models.CharField(max_length=255, verbose_name='Facor value')),
            ],
        ),
    ]
