# Generated by Django 2.2.5 on 2019-10-10 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_setfactor_setlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='setfactor',
            name='survey',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setlevel',
            name='set_factor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='surveys.SetFactor'),
            preserve_default=False,
        ),
    ]
