# Generated by Django 2.2.5 on 2019-10-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20191010_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setlevel',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Factor value'),
        ),
    ]
