# Generated by Django 2.2.5 on 2019-10-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_auto_20191010_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='setfactor',
            name='slug',
            field=models.SlugField(default=0, verbose_name='Factor slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setlevel',
            name='slug',
            field=models.SlugField(default=0, verbose_name='Factor slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setlevel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='factor Name'),
        ),
        migrations.AlterField(
            model_name='setlevel',
            name='value',
            field=models.CharField(max_length=255, verbose_name='factor value'),
        ),
    ]
