# Generated by Django 2.2.5 on 2019-10-11 13:23

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_auto_20191011_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='ready',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='setfactor',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Factor name'),
        ),
        migrations.AlterField(
            model_name='setlevel',
            name='slug',
            field=models.SlugField(verbose_name='Level slug'),
        ),
    ]
