# Generated by Django 3.0.3 on 2021-06-14 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_auto_20210517_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Session')),
            ],
        ),
    ]
