# Generated by Django 3.0.3 on 2021-06-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
