# Generated by Django 3.0.3 on 2021-06-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_delete_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='ai_method',
            field=models.CharField(default='method', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trial',
            name='context',
            field=models.CharField(default='context', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trial',
            name='explaination_approach',
            field=models.CharField(default='explanation', max_length=255),
            preserve_default=False,
        ),
    ]
