# Generated by Django 3.0.3 on 2021-06-14 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_auto_20210614_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='explaination_approach',
            new_name='explanation_approach',
        ),
    ]
