# Generated by Django 3.0.3 on 2021-06-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0014_auto_20210614_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='auswahl',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='bewertung_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='bewertung_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='bewertung_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='bewertung_4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='bewertung_5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='entscheidung',
            field=models.IntegerField(null=True),
        ),
    ]
