# Generated by Django 3.0.3 on 2021-06-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_auto_20210617_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='auswahl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trial',
            name='entscheidung',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
