# Generated by Django 3.0.3 on 2021-06-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_auto_20210617_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='auswahl',
            field=models.CharField(default='m', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trial',
            name='entscheidung',
            field=models.CharField(default='empfehlung', max_length=255),
            preserve_default=False,
        ),
    ]
