# Generated by Django 3.0.3 on 2021-06-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0018_auto_20210617_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='ai_recommendation',
            field=models.CharField(default='Medium (M)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trial',
            name='label',
            field=models.CharField(default='Medium (M)', max_length=255),
            preserve_default=False,
        ),
    ]
