# Generated by Django 3.0.3 on 2021-06-30 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_auto_20210629_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='entscheidung',
            new_name='decision',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='bewertung_1',
            new_name='rating_1',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='bewertung_2',
            new_name='rating_2',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='bewertung_3',
            new_name='rating_3',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='bewertung_4',
            new_name='rating_4',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='bewertung_5',
            new_name='rating_5',
        ),
    ]
