# Generated by Django 3.0.3 on 2021-06-30 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0020_auto_20210630_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='auswahl',
            new_name='choice',
        ),
    ]
