# Generated by Django 3.0.3 on 2021-07-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0021_auto_20210630_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='decision',
            field=models.IntegerField(null=True),
        ),
    ]
