# Generated by Django 3.0.3 on 2021-07-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0022_auto_20210701_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='end_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default='2021-07-04 15:00:00'),
            preserve_default=False,
        ),

    
    ]
