# Generated by Django 3.0.3 on 2021-07-16 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0023_auto_20210704_2200'),
    ]

    operations = [
        
    ]
