# Generated by Django 3.0.3 on 2021-07-16 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0024_auto_20210716_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='rating_4',
            new_name='certainty',
        ),

        migrations.RemoveField(
            model_name='trial',
            name='rating_5',
        ),
    ]
