# Generated by Django 3.0.3 on 2021-07-16 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0024_auto_20210707_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='rating_4',
            new_name='certainty',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='rating_5',
        ),
    ]
